# Day 28 - News Digest Bot (COMPLETE)

import requests
from bs4 import BeautifulSoup
from datetime import datetime

print("="*70)
print("        NEWS DIGEST BOT - WEEK 4 FINALE")
print("="*70)

# ============================================
# FUNCTIONS
# ============================================

def scrape_news():
    """Scrape news headlines"""
    
    print("\n📰 Scraping latest news...")
    
    url = "https://news.ycombinator.com/"
    
    try:
        response = requests.get(url, timeout=10)
        soup = BeautifulSoup(response.text, 'html.parser')
        
        titles = soup.find_all('span', class_='titleline')
        
        news_list = []
        
        for title in titles[:10]:
            link = title.find('a')
            if link:
                news_list.append(link.text)
        
        print(f"✅ Scraped {len(news_list)} headlines!")
        return news_list
    
    except Exception as e:
        print(f"❌ Error: {e}")
        return []


def create_digest(news_list):
    """Create formatted digest"""
    
    if len(news_list) == 0:
        return "No news available."
    
    today = datetime.now().strftime("%A, %B %d, %Y")
    
    digest = f"""
{'='*70}
                    DAILY NEWS DIGEST
{'='*70}

Date: {today}
Total Headlines: {len(news_list)}

{'='*70}
TOP STORIES:
{'='*70}

"""
    
    for i, headline in enumerate(news_list, 1):
        digest += f"{i}. {headline}\n\n"
    
    digest += f"""{'='*70}
Generated by News Bot at {datetime.now().strftime('%I:%M %p')}
{'='*70}
    """
    
    return digest


def save_digest(digest):
    """Save to file"""
    
    filename = f"news_digest_{datetime.now().strftime('%Y-%m-%d')}.txt"
    
    with open(filename, "w", encoding="utf-8") as file:
        file.write(digest)
    
    print(f"💾 Saved to: {filename}")
    return filename


def send_digest_email(digest, recipient):
    """Send email (simulated)"""
    
    print("\n" + "="*70)
    print("📧 NEWS DIGEST EMAIL SENT!")
    print("="*70)
    print(f"To: {recipient}")
    print(f"Subject: Daily News - {datetime.now().strftime('%B %d, %Y')}")
    print("="*70)
    print(digest)
    
    # Log it
    with open("sent_digests.txt", "a", encoding="utf-8") as file:
        file.write(f"\n{'='*70}\n")
        file.write(f"To: {recipient}\n")
        file.write(f"Sent: {datetime.now()}\n")
        file.write(digest)
    
    return True


def run_news_bot(email):
    """Run the complete bot"""
    
    print("\n🤖 Starting News Bot...")
    print("="*70)
    
    # Step 1: Scrape news
    news = scrape_news()
    
    if len(news) == 0:
        print("❌ No news found!")
        return
    
    # Step 2: Create digest
    print("\n📝 Creating digest...")
    digest = create_digest(news)
    
    # Step 3: Save to file
    print("\n💾 Saving digest...")
    filename = save_digest(digest)
    
    # Step 4: Send email
    print("\n📧 Sending email...")
    send_digest_email(digest, email)
    
    print("\n✅ News Bot completed successfully!")
    print(f"📁 Digest saved to: {filename}")
    print(f"📧 Email sent to: {email}")


# ============================================
# MENU
# ============================================

while True:
    print("\n" + "="*70)
    print("        NEWS BOT MENU")
    print("="*70)
    print("1. Run News Bot (Get Today's Digest)")
    print("2. View Saved Digests")
    print("3. Exit")
    print("="*70)
    
    choice = input("Choose (1-3): ")
    
    if choice == "1":
        email = input("Enter your email: ")
        run_news_bot(email)
    
    elif choice == "2":
        try:
            print("\n📂 SAVED DIGESTS:\n")
            with open("sent_digests.txt", "r", encoding="utf-8") as file:
                print(file.read())
        except FileNotFoundError:
            print("📭 No digests sent yet!")
    
    elif choice == "3":
        print("\n👋 Goodbye!")
        break
    
    else:
        print("❌ Invalid choice!")
